#!/usr/bin/env bash
# Install the FutuOpenD systemd user service.
# Run from the project root:  ./install.sh
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNIT_NAME="futuopend.service"
UNIT_SRC="${PROJECT_DIR}/systemd/${UNIT_NAME}"
UNIT_DST_DIR="${HOME}/.config/systemd/user"
ENV_FILE="${PROJECT_DIR}/.env"

echo "==> Checking prerequisites"
for var in FUTU_USER_ID FUTU_LOGIN_PWD_MD5 FUTU_OPEND_PORT FUTU_LOGIN_REGION; do
    if ! grep -qE "^${var}=.+" "${ENV_FILE}"; then
        echo "ERROR: ${var} is missing or empty in ${ENV_FILE}" >&2
        exit 1
    fi
done

OPEND_BIN="${HOME}/util/Futu_OpenD_10.9.6918_Ubuntu18.04/Futu_OpenD_10.9.6918_Ubuntu18.04/FutuOpenD"
if [[ ! -x "${OPEND_BIN}" ]]; then
    echo "ERROR: FutuOpenD binary not found or not executable: ${OPEND_BIN}" >&2
    exit 1
fi

echo "==> Securing ${ENV_FILE} (chmod 600)"
chmod 600 "${ENV_FILE}"

echo "==> Creating log directory"
mkdir -p "${PROJECT_DIR}/logs"

echo "==> Generating FutuOpenD config from .env"
CONFIG_DIR="${HOME}/.config/futuopend"
CONFIG_FILE="${CONFIG_DIR}/FutuOpenD.xml"
mkdir -p "${CONFIG_DIR}"
# shellcheck disable=SC1090
set -a; source "${ENV_FILE}"; set +a
cat > "${CONFIG_FILE}" <<EOF
<futu_opend>
    <!-- Generated by install.sh from ${ENV_FILE} -- do not edit by hand -->
    <ip>127.0.0.1</ip>
    <api_port>${FUTU_OPEND_PORT}</api_port>
    <login_account>${FUTU_USER_ID}</login_account>
    <login_pwd_md5>${FUTU_LOGIN_PWD_MD5}</login_pwd_md5>
    <lang>en</lang>
    <log_level>info</log_level>
    <log_path>${PROJECT_DIR}/logs</log_path>
    <push_proto_type>0</push_proto_type>
    <price_reminder_push>1</price_reminder_push>
    <auto_hold_quote_right>1</auto_hold_quote_right>
    <future_trade_api_time_zone>UTC+8</future_trade_api_time_zone>
    <pdt_protection>1</pdt_protection>
    <dtcall_confirmation>1</dtcall_confirmation>
</futu_opend>
EOF
chmod 600 "${CONFIG_FILE}"

echo "==> Installing ${UNIT_NAME} to ${UNIT_DST_DIR}"
mkdir -p "${UNIT_DST_DIR}"
cp "${UNIT_SRC}" "${UNIT_DST_DIR}/${UNIT_NAME}"

echo "==> Enabling lingering so the service starts at boot (may ask for sudo)"
if ! loginctl show-user "${USER}" --property=Linger 2>/dev/null | grep -q "Linger=yes"; then
    sudo loginctl enable-linger "${USER}"
fi

echo "==> Reloading systemd and enabling the service"
systemctl --user daemon-reload
systemctl --user enable "${UNIT_NAME}"
systemctl --user restart "${UNIT_NAME}"

sleep 3
echo "==> Service status"
systemctl --user --no-pager --full status "${UNIT_NAME}" || true

PORT="$(grep -oP '^FUTU_OPEND_PORT=\K[0-9]+' "${ENV_FILE}")"
if ss -tln 2>/dev/null | grep -q ":${PORT} "; then
    echo "==> OK: FutuOpenD is listening on 127.0.0.1:${PORT}"
else
    echo "WARNING: nothing listening on port ${PORT} yet — check: journalctl --user -u ${UNIT_NAME} -n 50" >&2
fi

echo
echo "Done. Useful commands:"
echo "  systemctl --user status ${UNIT_NAME}"
echo "  journalctl --user -u ${UNIT_NAME} -f"
echo "  systemctl --user restart ${UNIT_NAME}"
